FROM node:22.14.0

WORKDIR /forwardfootballassignment/frontend

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "node", "server/node-connection.js" ]