services:
  nextapp:
    build: 
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - nodeapp
    environment:
      - API_END_POINT=$${API_END_POINT_URL}
    networks:
      - next-node

  nodeapp:
    build: 
      context: ./backend
      dockerfile: DockerFile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    networks:
      - node-postgres
      - next-node

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: "./backend/.env"  
    #environment:
      #- POSTGRES_USER=$${POSTGRES_USER_NAME}
      #- POSTGRES_PASSWORD=$${POSTGRES_PASSWORD_CODE}
      #- POSTGRES_DB=$${POSTGRES_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - node-postgres

networks:
  next-node:
  node-postgres:

volumes:
  pgdata: