FROM node:22.15.0
WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma/
RUN npm install
RUN npm install -g prisma
COPY . .
RUN npm run build
RUN npm run prisma:generate
EXPOSE 8082
CMD ["sh", "-c", "if [ \"$SEED_DATABASE\" = true ]; then npm run prisma:push && npm run prisma:seed && npm run start:dev; else npm run prisma:push && npm run start:dev; fi"]